/**
 * Supabase Client Configuration
 *
 * This module provides typed Supabase client instances for both client and server contexts.
 * For local development with Supabase:
 * 1. Install Supabase CLI: https://supabase.com/docs/guides/cli/get-started
 * 2. Run: supabase init
 * 3. Run: supabase start
 * 4. Update .env.local with the provided credentials
 */

import { createClient } from '@supabase/supabase-js'
import { Database } from '@/types/database' // Will be generated by Supabase

// Environment variables - loaded from .env.local
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || ''

/**
 * Client-side Supabase client for use in browser/React components
 * Uses the Anon key which respects Row Level Security (RLS) policies
 */
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Recommended for Next.js App Router
  },
})

/**
 * Server-side Supabase client for use in API routes, Server Components, and Server Actions
 * Uses the Service Role key which bypasses RLS - use with caution!
 */
export function createSupabaseServerClient() {
  return createClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    process.env.SUPABASE_SERVICE_ROLE_KEY || '',
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    }
  )
}

/**
 * Admin client with full bypass of RLS - ONLY use in server contexts!
 */
export const supabaseAdmin = createSupabaseServerClient()

// Type helpers
export type SupabaseClient = typeof supabase
export type Database = Database
